local progress = require("visai.ui.progress")
local config = require("visai.config")

describe("progress", function()
  before_each(function()
    config.setup()
    progress.close()
  end)

  after_each(function()
    progress.close()
  end)

  describe("open", function()
    it("creates a floating window", function()
      progress.open()
      assert.is_true(progress.is_open())
    end)

    it("shows processing message", function()
      local state = progress.open()
      local lines = vim.api.nvim_buf_get_lines(state.bufnr, 0, -1, false)
      assert.are.same({ "AI is generating..." }, lines)
    end)
  end)

  describe("finish", function()
    it("shows success message", function()
      local state = progress.open()
      progress.finish(true)
      local lines = vim.api.nvim_buf_get_lines(state.bufnr, 0, -1, false)
      assert.matches("Done!", lines[1])
    end)

    it("shows default error message on failure", function()
      local state = progress.open()
      progress.finish(false)
      local lines = vim.api.nvim_buf_get_lines(state.bufnr, 0, -1, false)
      assert.matches("Failed%.", lines[1])
    end)

    it("shows custom error message when provided", function()
      local state = progress.open()
      progress.finish(false, "Job timed out after 20s")
      local lines = vim.api.nvim_buf_get_lines(state.bufnr, 0, -1, false)
      assert.matches("timed out", lines[1])
    end)

    it("does nothing when no window is open", function()
      assert.has_no.errors(function()
        progress.finish(true)
      end)
    end)
  end)

  describe("close", function()
    it("closes the floating window", function()
      progress.open()
      assert.is_true(progress.is_open())
      progress.close()
      assert.is_false(progress.is_open())
    end)

    it("does nothing when no window is open", function()
      assert.has_no.errors(function()
        progress.close()
      end)
    end)
  end)
end)
